### PR TITLE
feat: implements new methods in WebElement (Selenium 4.1.0)

### PR DESCRIPTION
**Pull request by papegaaij**
These methods have default implementations throwing an
UnsupportedOperationException, while most drivers support them. This
also fixes Select on Selenium 4.1.0.

### CODE REVIEW

**Comment by papegaaij** [comment]
With this change, I see no reason for `GrapheneSelect` anymore. Do you want me to remove it as part of this PR?

**Comment by bartoszmajsak** [comment]
> With this change, I see no reason for `GrapheneSelect` anymore. Do you want me to remove it as part of this PR?

Absolutely! Thank you very much for this contribution.

**Comment by papegaaij** [comment]
I've pushed a commit that removes GrapheneSelect and its implementation. All tests pass and in our own codebase we use Select quite a lot and it works fine now.

**Comment by bartoszmajsak** [comment]
Could you also remove mentions from the docs? Namely `docs/location-strategies.adoc`

**Comment by bartoszmajsak** [comment]
Can you also merge changes from `master`? With that, I think we are good to go.

**Review by bartoszmajsak — APPROVED** [review]
Thank you very much! As soon as the newest Drone lands in Maven Central I will cut the release of Graphene. It should be today, as the release of Drone was done last night.

**Comment by bartoszmajsak** [comment]
@papegaaij Drone has been released but for unknown reason they haven't been synced with Maven Central. You can grab Drone from JBoss Repository while I'm trying to figure out how to re-sync it...

https://repository.jboss.org/ (e.g. https://repository.jboss.org/org/jboss/arquillian/extension/arquillian-drone-api/3.0.0-alpha.2/)

**Comment by papegaaij** [comment]
It seems something is wrong with the sync. WildFly has the same issue: https://lists.jboss.org/archives/list/wildfly-dev@lists.jboss.org/thread/OLHV2CZ4XHMIYXYJQJC26A35CJW7EO2U/

**Comment by bartoszmajsak** [comment]
@papegaaij even though (official search)[https://search.maven.org/search?q=arquillian%20drone) does not show it's synced, it seems it's available in official repo: https://repo1.maven.org/maven2/org/jboss/arquillian/extension/arquillian-drone-impl/3.0.0-alpha.2/

Could you check on your end if that works fine?

**Comment by papegaaij** [comment]
Yes, they work fine here. I'm able to download the artifacts via our local artifactory mirror.

**Comment by bartoszmajsak** [comment]
@papegaaij I'm releasing graphene with your changes now. Thanks again!

**Pull request merged**
