### PR TITLE
ARQGRA-476 - Extend root element from GrapheneElement

### PR DESCRIPTION
**Pull request by michbeck100**
http://issues.jboss.org/browse/ARQGRA-476

### CODE REVIEW

**Comment by michbeck100** [comment]
This pull request is based on https://github.com/arquillian/arquillian-graphene/pull/133

**Comment by lfryc** [comment]
Thanks @michbeck100 , nice addition! Merging :rocket:

**Comment by michbeck100** [comment]
Thanks for merging!

**Comment by lfryc** [comment]
@michbeck100 @MatousJobanek I'd like to release `Alpha3` in two weeks, let me know if you'd appreciate it earlier.

**Comment by michbeck100** [comment]
I'm fine with that.

**Comment by MatousJobanek** [comment]
@lfryc in two weeks is OK :+1:

**Pull request merged**
