### PR TITLE
ARQGRA-484 changed GrapheneElementImpl's equals & hashcode

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by lfryc** [comment]
@MatousJobanek @jstefek this seems like a nice feature, but I'm afraid it breaks equals/hashCode contract:

* objects are equal specifically when they are of the same type

This fix afaik means that WebElement can be equal to GrapheneElementImpl - which as I said may be a nice feature, but question is if we should intentionally break the contract.

**Comment by lfryc** [comment]
@MatousJobanek could you please cherry-pick the tests from https://github.com/arquillian/arquillian-graphene/pull/155 here?

**Comment by MatousJobanek** [comment]
@lfryc to be honest I was inspired by this commit https://github.com/arquillian/arquillian-graphene/commit/0963bb5e12dcb4947403e3126084f4bb364eab1f and I didn't realized that it breaks the reflection. The test case was cherry-picked

**Comment by bartoszmajsak** [comment]
@MatousJobanek what do we do with this PR? :)

**Comment by VsevolodGolovanov** [comment]
> objects are equal specifically when they are of the same type

There is no such contract for equals/hashCode.

>     the equals has to be reflective relation
> 
> Without testing, I bet GrapheneElementImpl.equals(WebElement), but ! WebElement.equals(GrapheneElementImpl)

This is symmetry, not reflexivity.
Selenium's RemoteWebElement unwraps the other element in its equals. So the symmetry is present.

There are other problems though.
```
if (obj instanceof GrapheneElementImpl) {
    obj = ((GrapheneElementImpl) obj).element;
}
return element.equals(obj);
```
`obj instanceof GrapheneElementImpl` would most of the time evaluate to false because obj would be a proxy. So the execution would move on to `element.equals(obj)`, where it relies on Selenium's RemoteWebElement#equals to unwrap the obj (via the WrapsElement interface and its getWrappedElement() method). Might as well rely on it in case of `obj instanceof GrapheneElementImpl` evaluating to true. In fact, whenever there are proxies involved, code like `otherObj.privateField` seems iffy. What if a proxy sometimes extends the Impl class?

But sometimes a proxy doesn't implement WrapsElement, because it doesn't proxy a GrapheneElement, but a RemoteWebElement directly. E.g. `driver.switchTo().activeElement()`. This may be a separate bug... GrapheneElementImpl#equals could unproxify `obj` in such a case or it could throw an exception, if this is a bug.

**Comment by bartoszmajsak** [comment]
Thanks for clarifications @VsevolodGolovanov. Would you be interested to help us fixing it further?

**Comment by VsevolodGolovanov** [comment]
@bartoszmajsak, I would, if @MatousJobanek doesn't mind. Though I'm not sure how to go about it since I won't be able to add commits to this PR without write access to MatousJobanek's repo...

**Comment by MatousJobanek** [comment]
Hi, sorry for my late response. As @VsevolodGolovanov  has written, it is not so easy as it seemed to be.  I did some short research when I was dealing with the issue, but because of lack of time, I had to park it for while.
@VsevolodGolovanov you seem to have a deeper understanding of this issue than I have, so would really appreciate if you helped me with it.

**Comment by MatousJobanek** [comment]
@VsevolodGolovanov I would be really thankful.
I changed the access rights to this commit so feel free to send any commit you have.

**Comment by MatousJobanek** [comment]
Ah dammit, @VsevolodGolovanov I didn't realize that I can allow a write access only for maintainers and you're not a maintainer. 
Please, open a new PR, cherry-pick the test and then we can close this one.

**Comment by MatousJobanek** [comment]
Closing as it is fixed by  https://github.com/arquillian/arquillian-graphene/pull/164

**Pull request closed without merging**
