### PR TITLE
ARQGRA-477 Update arquillian-core to 1.1.9.Final

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by MatousJobanek** [comment]
I attached also a commit with an update of jboss-parent to the newest version: 19

**Comment by MatousJobanek** [comment]
retest this please - I tested it locally and it worked

**Comment by MatousJobanek** [comment]
retest this please

**Comment by MatousJobanek** [comment]
I attached an update of Arquillian Recorder to 1.1.0.Alpha3

**Comment by MatousJobanek** [comment]
I attached an update of jboss-parent to version 16 (as the latest version that the Graphene should be compatible with)

**Comment by lfryc** [comment]
Thanks @MatousJobanek !

**Pull request merged**
