### PR TITLE
Release 2.1.0.alpha3

### PR DESCRIPTION
**Pull request by MatousJobanek**
Staged at https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-6948/

### CODE REVIEW

**Comment by lfryc** [comment]
Yay, thanks @MatousJobanek !!

**Comment by lfryc** [comment]
@MatousJobanek I've merged this to master and pushed `2.1.0.Alpha3` tag.

The JIRA version also shows everything resolved for the version: https://issues.jboss.org/projects/ARQGRA/versions/12328588

Could you please release staging profile?

Once that happens, we can ping Aslak to release a blog.

**Comment by MatousJobanek** [comment]
Hi @lfryc 
I released the staging profile, so probably tomorrow it could be available on maven central.

**Comment by MatousJobanek** [comment]
It's already available in the maven central. @lfryc please mark as closed/released the version 2.1.0.Alpha3 there in the Jira. If you don't want to mention anything there in the blog post, then we can ask @aslakknutsen for announcing this new release.

**Comment by lfryc** [comment]
Hi @aslakknutsen , could you please publish a blog for Graphene `2.1.0.Alpha3`?

We don't need any release notes except the ones that will be generated automatically:
https://issues.jboss.org/secure/ReleaseNote.jspa?projectId=12312222&version=12328588

**Comment by aslakknutsen** [comment]
on it

**Comment by aslakknutsen** [comment]
done, pushed live, announced! Good work, guys! :dancers: :beers:

**Comment by lfryc** [comment]
Yay, :rocket: :new_moon:

**Pull request merged**
