### PR TITLE
2.1.0.Beta1 release

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by MatousJobanek** [comment]
Staged at https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-7891

**Comment by lfryc** [comment]
@MatousJobanek I wonder have you ran some tests on the stages bits?

**Comment by MatousJobanek** [comment]
Yeah, the standard test suite. Nothing additional.

**Comment by MatousJobanek** [comment]
Do you face any problem?

**Comment by lfryc** [comment]
Nope, we are good to go. I will merge this shortly and we can continue with
a release. Thanks Matous!

On Wed, Mar 23, 2016 at 12:36 PM, Matous Jobanek <notifications@github.com>
wrote:

> Do you face any problem?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/arquillian/arquillian-graphene/pull/156#issuecomment-200307831>
>



-- 
Lukáš Fryč
Software Engineer
Red Hat Mobile | AeroGear.org, FeedHenry.org

**Comment by MatousJobanek** [comment]
Today, I ran the whole Keycloak integration-arquillian testsuite with the Graphene Beta1 and it passed ;-)

**Comment by MatousJobanek** [comment]
So, may I release it?

**Comment by lfryc** [comment]
Perfect, thanks @MatousJobanek , merging now!

**Pull request merged**
