### PR TITLE
alignement of dependencies for Drone 2.0.0.Alpha3

### PR DESCRIPTION
**Pull request by smiklosovic**
@lfryc

### CODE REVIEW

**Comment by smiklosovic** [comment]
@lfryc Drone 2.0.0.Alpha3 is out, you can proceed with the merge

**Comment by aslakknutsen** [comment]
@smiklosovic out? no sign of it on github? https://github.com/arquillian/arquillian-extension-drone/releases

**Comment by smiklosovic** [comment]
@aslakknutsen yes we will take care of it the next week, we are rushing with releases, graphene will follow and droidium will finish it since it depends on both.

**Comment by smiklosovic** [comment]
@lfryc the lastly push commit relates to this issue https://github.com/arquillian/arquillian-recorder/issues/10

**Comment by lfryc** [comment]
Merged: https://github.com/arquillian/arquillian-graphene/commit/f210b6d75c401046fb54fc0d585e68fbed74a29f

**Pull request closed without merging**
