### PR TITLE
Screenshooter tests

### PR DESCRIPTION
**Pull request by MatousJobanek**
tests covering:
ARQ-1979
ARQGRA-480 
ARQGRA-482
and other usecases

this PR depends on the PRs:
#139 
#140 
#141

### CODE REVIEW

**Comment by smiklosovic** [comment]
:+1:

**Comment by smiklosovic** [comment]
it seems like tests are broken, dunno what is causing the error ...

**Comment by MatousJobanek** [comment]
It's not broken - it just depends on other PRs (containing fixes) as I mentioned above...

**Comment by smiklosovic** [comment]
sorry :) so I am double thumbing this up :) :+1: :+1:

**Comment by lfryc** [comment]
Hey @MatousJobanek I :heart:  these tests,

but unfortunately they fail for me when I rebased this branch on master: https://github.com/arquillian/arquillian-graphene/pull/143

Stacks:
https://gist.github.com/lfryc/436a4ac99560f7ddf394

**Comment by MatousJobanek** [comment]
This is really weird since I cannot reproduce this problem locally. I fetched the branch #143 and ran the tests several times and it is passing.

**Comment by lfryc** [comment]
@MatousJobanek they fail for me on Fedora 21 locally.

**Comment by MatousJobanek** [comment]
Found out where is the problem - both the TestInstanceEnricher [1] and ScreenshooterLifecycleObserver [2] has the very same precedence = 0, so it is just question of luck what is called first. When the ScreenshooterLifecycleObserver is called before the TestInstanceEnricher then no instance of Drone is available and the exception is thrown.

[1] https://github.com/arquillian/arquillian-core/blob/master/test/impl-base/src/main/java/org/jboss/arquillian/test/impl/TestInstanceEnricher.java#L46
[2] https://github.com/arquillian/arquillian-recorder/blob/master/arquillian-recorder-screenshooter-base/arquillian-recorder-screenshooter-impl-base/src/main/java/org/arquillian/extension/recorder/screenshooter/impl/ScreenshooterLifecycleObserver.java#L69

**Comment by MatousJobanek** [comment]
Related issue https://issues.jboss.org/browse/ARQ-1993

**Comment by lfryc** [comment]
Ok, once reporter is staged, we are good to merge this.

**Comment by MatousJobanek** [comment]
Attached a commit with the update of Arquillian Recorder to 1.1.0.Alpha4

**Comment by MatousJobanek** [comment]
Attached a commit with an update of Arquillian core to the newest one 1.1.10.Final. (I know that it is not related to screenshooter tests, but I don't think that it is necessary to create a new PR.)

**Comment by lfryc** [comment]
Seems that BuildHive is slacking...

**Comment by lfryc** [comment]
Verified locally and merged!

**Comment by lfryc** [comment]
Thanks @MatousJobanek !!

**Comment by lfryc** [comment]
there wasn't any associated jira, right?

**Comment by MatousJobanek** [comment]
No, there wasn't

**Pull request merged**
